### ISSUE TITLE
Trigger ignores trigger-active and fires during register

### ISSUE THREAD

**Issue by jfedyczak** [princemaple/scroll-trigger#10]
The `register` method doesn't evaluate `item.busy`. So `item.action` is called regardless of `trigger-active` value. It seems that adding `... && !item.busy()` to the `if` before `item.action()` fixes that.

**Comment by princemaple** [comment]
Hi @jfedyczak , thanks for reporting :)
This should have been fixed by https://github.com/princemaple/scroll-trigger/commit/18b18204330a4f58037495e092aeebe86d1cb181
I've released v0.5.4 for the fix.

**Comment by princemaple** [comment]
I'll leave this one for you to close, since I didn't personally test the effect of the change, only tested in my mind :wink:

**Comment by jfedyczak** [comment]
Works fine. Thanks!

**Comment by princemaple** [comment]
:)
