### ISSUE TITLE
How to lazy load images inside scroll container?

### ISSUE THREAD

**Issue by diogodomanski** [princemaple/scroll-trigger#6]
Is there a way to define another container element other than "window" (default one)? I have a list of images inside a scrolling div, but scroll-trigger is taking into account only window scrolls.

I don't want to load the list items progressively (like an infinite scroll), I just want to lazy load images inside my list.

**Comment by princemaple** [comment]
Hi @diogodomanski I have an example for that.
https://github.com/princemaple/scroll-trigger/blob/master/test/test_scroll_container.html

Feel free to reopen if you have further questions! :)

**Comment by diogodomanski** [comment]
Hi @princemaple. Thanks for your reply. I had already seen this example, but it doesn't do what I need.

I don't want to load the items progressively, instead I need to load the whole list at once (inside a scrolling div) and then load images as they become visible. It's a mix between the example you've mentioned and this one https://github.com/princemaple/scroll-trigger/blob/master/test/test_img_src_ondemand.html.

I've only found examples for lazy loading images when the window scrolls. Is there a way to do the same but when the items are placed inside another scrolling container (a div, for instance)?

**Comment by princemaple** [comment]
I see, let me do a quick test

**Comment by princemaple** [comment]
Hi @diogodomanski ,

I've added some new functionality and a [new test](https://github.com/princemaple/scroll-trigger/blob/master/test/test_lazy_img_in_container.html), and released a new version `v0.5.0`

Hope this helps :)

**Comment by princemaple** [comment]
Close this issue if you find the new functionality / test works for you. Thank you!

**Comment by diogodomanski** [comment]
That's exactly what I need. Thank you very much.

**Comment by princemaple** [comment]
You are welcome!
